### ISSUE TITLE
Build failure with recent GCC

### ISSUE THREAD

**Issue by mattcode55** [rapidhashing/node-cryptonote-util#1]
```
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
make: *** [cryptonote.target.mk:111: Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/matt/.src/node-cryptonote-pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/matt/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.11.10-300.fc26.x86_64
gyp ERR! command "node" "/home/matt/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

**Comment by mattcode55** [comment]
Ref: https://github.com/monero-project/monero/issues/834
